### ISSUE TITLE
SSP model exchange between OMSimulator and easySSP fails

### ISSUE THREAD

**Issue by olivleno** [OpenModelica/OMSimulator#1094]
### Description

I tried to build a simple SSP model in OMSimulator and easySSP by exxcellent solutions and exchange it either way.

### Steps to reproduce the behavior

Create model in OMSimulator. 
Save as SSP.
Import in easySSP: Validation failed error

Create model in easySSP. 
Save as SSP.
Open in OMSimulator: [3] 08:04:07 Scripting Error
[NewModel] "Root-System" is not a valid ident

Not clear what I' supposed to do with the below:
 ```Lua
-- Print version string
version = oms_getVersion()
print(version)

...
```

### Expected behavior

Show the loaded model as created in the other tool.

### Screenshots

Is available but upload failed.

### Version and OS

- Version: OMSimulator v2.1.1.post80-g1bf17f4-mingw
- OS: Win10, 64bit

**Comment by arun3688** [comment]
@olivleno Currently `OMSimulator` does not import `ssp` from other tools due to  internal `oms_solver`  information needed in `<oms:Annotations>` , given below.

```
<ssd:Annotations>
    <ssc:Annotation type="org.openmodelica">
        <oms:Annotations>
            <oms:SimulationInformation>
                <oms:FixedStepMaster description="oms-ma" stepSize="0.001000" absoluteTolerance="0.000100" relativeTolerance="0.000100" />
            </oms:SimulationInformation>
        </oms:Annotations>
    </ssc:Annotation>
</ssd:Annotations>
```
We are currently working on this issue, to import `SSP` from all tool vendors, But the reverse should be possible export an `ssp` from `OMSimulator`  and it should be imported in other tools, we checked our exported `ssp` with `easySSP` and it got successfully validated.

I can see that you are using old version of OMSimulator, `OMSimulator v2.1.1.post80-g1bf17f4-mingw` I guess in this version our `SSP` had validation problem with `easySSP`, 

Please checkout the latest version of OMSimulator and our exported `SSP ` should work with `easySSP`

**Comment by olivleno** [comment]
Ok good to know. Latest version refers to the nightly build I guess.
Thanks for the feedback. Will try it someday later then.

**Comment by lochel** [comment]
You can simply test it using the python package (pip install OMSimulator) if you don't want to mess with your OpenModelica installation.
