### ISSUE TITLE
C API Windows

### ISSUE THREAD

**Issue by tarasborov** [OpenModelica/OMSimulator#1137]
I have installed an OpenModelica with shipped OMSimualor. Now, I am going to use C API to run OMSimulator from C++ code. Unfortunately, the OMSimulator can not be found in CMakeLists.txt file included in my custom package: find_package(OMSimulator REQUIRED) 

- Version: OpenModelica v1.18.1 (64-bit) Connected to OMSimulator v2.1.1.post80-glbf17f4-mingw
- OS: Win10, 64bit

**Comment by lochel** [comment]
@mahge, can you comment on this one?

**Comment by mahge** [comment]
I am not sure if I understood correctly. You have installed OpenModelica and want CMake to find it the same way it finds boost, for example. Is this correct? 

CMake itself does not know about OpenModelica in that way. You would have to tell CMake where to find OpenModelica files explicitly. You can do this by writing a custom `FindOpenModelica.cmake` file if you want. Same procedure if you want to use OMSimulator.

You can see some examples of how to find write and use custom find modules here:
https://riptutorial.com/cmake/example/22950/use-find-package-and-find-package--cmake-modules

https://github.com/rpavlik/cmake-modules/blob/main/module-docs/Example-FindMyPackage-UsingImportedTargets.cmake

There should be many more examples on the web.

We should probably write one such module and ship it with our installation to simplify things. We will do that as soon as possible. In the meantime you can write one just for your setup only.

Hint. You can also try just linking to the libraries you want without using a find_package call beforehand. All you need to do is add a `target_link_directories()` call to the location of the libraries on your machine. You can also just use `find_library()` instead of `find_package`. You might have to add the include directories manually as well using `target_include_directories()`.

**Comment by tarasborov** [comment]
Thank you for your explanation. It helped.
