### ISSUE TITLE
Co-simulation FMU prints double rows

### ISSUE THREAD

**Issue by Thewodoros** [OpenModelica/OMSimulator#1196]
### Description

I tried to make an FMU out of Amesim’s tutorial model, the driveline, and then launch it in OMSimulator (python library). But for every step, it prints the same row in the CSV result file twice: two lines for time=0.0001, two for time=0.0002, etc.

### Version and OS

- Version: 2.1.1.post190, installed through pip
- OS: Win10 22H2, 64bit

**Comment by MathiasMalandain** [comment]
Up on this one. I have a simple test case with two FMUs (basically, FMU1 produces a value, FMU2 consumes it). With fixed time step 1, I get one row for t=0, then two for t=1, two for t=2, etc. until I reach the end time, at which point I get 3 rows.

For each time point, the input value for FMU2 (directly sent by FMU1 after its time stepping) is updated between the first and second rows.

This is a weird behavior, although I at least know that only keeping the "odd numbered rows" in the output file yields what was expected.

## Version and OS

* Version: 2.1.1~247-g614c663-linux-notlm-debug
* OS: Ubuntu22.04 (64bit)

**Comment by lochel** [comment]
@Thewodoros, @MathiasMalandain Apologies for the delayed response. We’ve regained momentum on this project recently and implemented numerous fixes and improvements over the past few weeks. I’ve also published a new pip package.

Testing the behavior with the DualMassOscillator example from the test suite, I observed that each timestep is now reported only once in the result file. While I’m unsure exactly when this issue was resolved, it appears to be fixed.

Please feel free to reopen this issue if you encounter any further problems.
