### ISSUE TITLE
Implement proper state event detection in OMSimulator

### ISSUE THREAD

**Issue by casella** [OpenModelica/OMSimulator#1271]
Currently, OMSimulator only checks for event-triggering conditions (e.g. zero-crossing functions changing their sign) at each time step, but doesn't try to figure out the exact time when the zero-crossing function changed sign. This results in delays of up to one time step in the triggering of events. 

In many cases this is no big deal, but in some cases this may seriously change or disrupt the simulation results.

We should eventually implement a proper state event detection mechanism in OMSimulator.

**Comment by rruusu** [comment]
One easy step to improve the accuracy of event processing, in lieu of implementing a more accurate zero-crossing solver, at least when using CVODE,  would be to check for events after each integrator step instead of the precision provided by the maximum time step size, as is currently done by [oms::SystemSC::doStep](https://github.com/OpenModelica/OMSimulator/blob/f48ed62ded2514b242cd85898043247d08973e1b/src/OMSimulatorLib/SystemSC.cpp#L486)

I will push an implementation for this to my fork shortly.

**Comment by casella** [comment]
Please make a PR out of it so we can run it on our testsuite and see what happens

**Comment by lochel** [comment]
Thanks for bringing up this issue, @casella and @adrpo! After reviewing the code, I could definitely see room for improvement (especially since I wrote it originally!). To address this, I created a minimal example together with @arun3688 and implemented state event detection for the explicit euler method, which is showing good results so far.

@rruusu, I plan to open a pull request next week - feel free to take a look and comment on it. If you’ve already started working on a similar implementation, it would be great to combine our approaches for the best outcome.

Some tasks still on my list:

* integrate with time events
* add support for CVODE

I’ll keep everyone updated as I make progress.

**Comment by lochel** [comment]
I'll keep this open until we have a [master-fmi](https://libraries.openmodelica.org/branches/master-fmi/) report to verify that my changes are working as expected.

**Comment by casella** [comment]
Will also be interesting to compare the performance of OMSimulator and FMPy 😃

**Comment by lochel** [comment]
The new implementation appears to be working well, so I will close this issue. If you encounter any further problems or have additional suggestions, please feel free to open a new issue. Thank you!
