### ISSUE TITLE
Running reference model BouncingBall.fmu causes infinite prints (error:   [doStep] SUNDIALS_ERROR: CVode() failed with flag = -3)

### ISSUE THREAD

**Issue by GorbadPS3** [OpenModelica/OMSimulator#1281]
### Description

Running reference model BouncingBall.fmu causes infinite prints in console:

```
[CVODE ERROR]  CVode
  At t = 0.446 and h = 0.001, the error test failed repeatedly or with |h| = hmin.

error:   [doStep] SUNDIALS_ERROR: CVode() failed with flag = -3
```

### Steps to reproduce the behavior

1. Download https://github.com/modelica/Reference-FMUs/releases/tag/v0.0.29
2. Unzip
3. Locate Reference-FMUs-0.0.29/2.0/BouncingBall.fmu
4. Run the following OMSimulator.dll commands:

```
        oms_setTempDirectory("C:/local/foobar/temp");
    	oms_newModel("m");
    	oms_addSystem("m.r", oms_system_sc);
    	oms_addSubModel("m.r.BB", "./Reference-FMUs-0.0.29/2.0/BouncingBall.fmu");
    	oms_setResultFile("m", "C:/local/foobar/result/results.csv", 100);
    	oms_setStopTime("m", 1.0);
    	oms_setStartTime("m", 0.0);
    	oms_setFixedStepSize("m.r", 0.001);
    	oms_instantiate("m");
    	oms_initialize("m");
    	oms_simulate("m");
    	oms_terminate("m");
    	
```

Notice that as soon as you call "oms_simulate" the console will start filling with errors.

### Expected behavior

The simulation should finish as expected. Running OMSimulator.exe from command-line works fine:

OMSimulator.exe --startTime=0.0 --stopTime=1.0 --resultFile="C:/local/foobar/result/results.csv" "./Reference-FMUs-0.0.29/2.0/BouncingBall.fmu"

### Version and OS

- Version: v2.1.1.post247-g614c663-mingw-notlm-debug
- OS: Win11, 64bit

**Comment by GorbadPS3** [comment]
Hi,

Thanks, that makes sense. What doesn't make sense is OMSimulator going into an infinite loop. The code should be able to notice the issue and return oms_status_error in cases like this.

**Comment by lochel** [comment]
Thanks for reporting the issue, @GorbadPS3. I’ve improved the error handling so that OMSimulator now stops after doStep fails the first time, avoiding the infinite loop of error messages. Beyond that, I’d like to provide some additional context about what’s happening here and why, as I understand it can be a bit confusing if you’re not familiar with the internals of OMSimulator. I’m also open to any suggestions for further improving the situation!

### What's going on?

When you call `oms_setFixedStepSize`, it forces CVODE into using fixed step sizes by setting the initial, minimum, and maximum step size to the same value. This is usually **not** ideal for CVODE, as it performs better with variable step sizes tailored to the problem's dynamics.

However, you're right that printing error messages in an infinite loop is bad behavior. We've addressed this, and here's the new output for your test case:

```
info:    maximum step size for 'm.r': 0.001000
info:    Result file: results.csv (bufferSize=100)

[CVODE ERROR]  CVode
  At t = 0.446 and h = 0.001, the error test failed repeatedly or with |h| = hmin.

error:   [doStepCVODE] CVode failed with flag = -3
warning: Bad return code at time 0.446000
info:    Final Statistics for 'm.r':
         NumSteps = 446 NumRhsEvals  = 455 NumLinSolvSetups = 23
         NumNonlinSolvIters = 454 NumNonlinSolvConvFails = 0 NumErrTestFails = 1
info:    1 warnings
info:    1 errors
```

### Variable Step Sizes

The model runs smoothly when using **variable step sizes** instead of a fixed step size. You can configure this with:

```lua
oms_setVariableStepSize("m.r", 1e-6, 1e-6, 1e-3);
```

This setup is similar to the default parameters used when running the model from the command line. For reference, these are the default values:

```
  minimumStepSize = 1e-12
  maximumStepSize = 1e-3
  initialStepSize = 1e-6
```

Thanks again for reporting the issue, and best of luck using OMSimulator in the future!
