### ISSUE TITLE
Logging and plotting of data

### ISSUE THREAD

**Issue by lochel** [OpenModelica/OMSimulator#169]
- [x] Selection of variables to store and plot
- [x] Subsample simulation for logging
- [x] Split up the result files into several smaller ones instead of one large when simulating sequentially
- [x] Allow to skip writing a result file
- [x] Make buffer size adjustable

**Comment by meek1** [comment]
Needed in Release v2.0.

**Comment by meek1** [comment]
Any examples in the test suite or in documentation on how to use setVariableFilter?

**Comment by lochel** [comment]
Not yet, but I will add one as soon as this feature is available.

**Comment by meek1** [comment]
OK, in the meantime, is it possible to simulate sequentially to split up the result files into several smaller ones instead of one large? I tried the following but it resulted in only one result file named "result1.mat":

-- simulation settings
oms2_setCommunicationInterval("AVSDemo", 1e-3)
-- *** 1st simulation sequence ***
oms2_setResultFile("AVSDemo", "result1.mat")
oms2_setStopTime("AVSDemo", 0.02)
oms2_initialize("AVSDemo")
oms2_simulate("AVSDemo")

-- *** 2nd simulation sequence ***
oms2_setResultFile("AVSDemo", "result2.mat")
oms2_setStartTime("AVSDemo", 0.02)
oms2_setStopTime("AVSDemo", 0.04)
oms2_simulate("AVSDemo")

**Comment by meek1** [comment]
A really nice feature would be to select which variable NOT to store, e.g. all concealed* for black-box FMUs. For several test FMUs, the majority of variables are concealed*.

**Comment by meek1** [comment]
@lochel, when can we expect a first functionality to specify plot interval/down sampling for FMI composite models? It is very needed. For the test cases I'm running, I need a communication interval of approx. 1e-3s for stability reasons but I'm only interested in results data of say 1Hz.

I don't want the spcified plot interval to force the master to take exact steps of certain lenght, rather data should be interpolated from available points (or as a first version take the point closest to the specified if this is significantly less implementation work).

**Comment by lochel** [comment]
@meek1 #237 will provide a new API to specify a logging interval. This approach doesn't use any interpolation. It just skips data point which are too close in time. It works already, but I have to test it a bit more before merging (probably later today).

**Comment by lochel** [comment]
Usage of the new functioanlity: `oms2_setLoggingInterval("model", value)`
```
value E (-inf; 0):                  logging disabled
value E [0; communicationInterval]: logging of all data
value > communicationInterval:      reducing the size of the result file by skipping some data points
```

**Comment by lochel** [comment]
@meek1 It shouldn’t matter when you set the logging interval. It is also possible to change it within a single simulation. The following works for me:
```Lua
-- *** initialization ***
oms2_setResultFile("AVSDemo","result_init.csv")
oms2_setStopTime("AVSDemo",5)
oms2_initialize("AVSDemo")
oms2_setCommunicationInterval("AVSDemo", 1e-5)
oms2_stepUntil("AVSDemo", 1e-4)
oms2_setCommunicationInterval("AVSDemo", 1e-4)
oms2_stepUntil("AVSDemo", 1e-1)

-- *** simulatation ***
oms2_setCommunicationInterval("AVSDemo", 1e-3)
oms2_setLoggingInterval("AVSDemo", 1e-1)
oms2_simulate("AVSDemo")
```

**Comment by lochel** [comment]
What are the error messages that you get?

**Comment by meek1** [comment]
@lochel, please have a look at the test case in OpenCPS repo: \WP6\T6.3\test_setLoggingInterval

**Comment by lochel** [comment]
Btw, I also used OMSimulator v0.1.0-476-gd4b69d4-win.

**Comment by lochel** [comment]
I investigated this a bit more and it seem to be in fact a problem with the FMU itself. If I do not fetch all internal real variables (e.g. for writing them to result file) then this model will crash.

**Comment by lochel** [comment]
Exactly, therefore I believe that it must be a problem with the FMU itself.

**Comment by meek1** [comment]
OK, could it have anything to do with black-box FMUs? Most FMUs in the test case are black-box and have lots of conceald variables. In modelDescription.xml, the causality of the concealed varaibles is not defined, i.e. they are not input, not output, not parameters. Maybe these needs to be updated for each doStep (or something...)?

**Comment by meek1** [comment]
Dymola 2018 FD01, good idea for long term FMU generation enhancements. Can you come up with some workaround enabling the master to handle FMUs with this (strange) behavior? E.g. perform doStep exactly as before and log everything as before at each communication point, but to a temporary mat/csv file of limited size. Then during simulation interpolate from the temporary file based on oms2_setLoggingInterval and write to a new result file including only interpolated values.

**Comment by meek1** [comment]
Don't know if it helps but FYI I also get this warning when using setLoggingInterval: AVSDemo.engine (): CVODE: CVode failed with CV_TOO_CLOSE: tout too close to t0 to start integration.

**Comment by meek1** [comment]
@lochel, we need a workaround so that setLoggingInterval works also for this kind of FMUs. Until the FMU generation has been investigated by the tool vendor, maybe there could be two options in OMSimulator, something like:
1) "always get all variables at each communication point" (as with no setLoggingInterval)
2) "only get outputs at each communication point".

For efficienfy, I guess such option should be set on individual FMU level. To start with, a quick fix is needed so the simulation runs with setLoggingInterval for current FMUs.

I've now tried the following FMU types:
* Black box Cvode: "Original" version, stuck with warning.
* White box Cvode: Similar behavior, stuck but no warning.
* Black box Dassl: Takes forever to initialize.
* Black box Radau: Takes forever to initialize.

Even though it seems like the problem is in the FMUs and the FMU generation should then be corrected, it is in fact a quality of the master to be able to cope with poor FMUs. Not tailoring the master to specific FMU generation tools, but providing general functionality to workaround various problems.

**Comment by lochel** [comment]
I think everything is now implemented and fixed. Please open a new issue if anything is not working as expected.

**Comment by meek1** [comment]
Is the workaround also implemented? How do I activate/deactivate?

**Comment by lochel** [comment]
You can try `oms2_setFlags("Model.FMU", "+fetchAllVars")` to enable the requested workaround as soon as #252 is merged.
