### ISSUE TITLE
Printout line of error 

### ISSUE THREAD

**Issue by robha67** [OpenModelica/OMSimulator#516]
It is difficult to locate composite modeling errors for large models expressed in Lua. Printing out the line of the error in the lua script (in the log file and the command window) would simplify debugging drastically. For example: the following error is communicated in the log file

 | error:   [addConnectorToTLMBus] Not available for TLM systems

To identify the connector that poses the problem is most time consuming if hundreds of connectors exist in the model.

**Comment by lochel** [comment]
Yes, I agree and it is a good example for a bad error message. However, we cannot print the line number, because the Lua scipt is processed by the Lua interpreter.
I think error messages should always dump the system/component/connector/… that is involved. Also wrong arguments should be printed to make it easy to spot the correspondent call in the scripts. I tried to improve most of the error messages during the last weeks. @robbr48, can you please improve the TLM related messages?

**Comment by sjoelund** [comment]
Can't you query this from Lua? https://stackoverflow.com/questions/2555856/current-line-number-in-lua

**Comment by lochel** [comment]
Yes, that is possible. However, we need improved messages anyway for the C-API.

**Comment by robbr48** [comment]
@lochel Sure, but do you mean that we should replace all `logError_NotForTlmSystem` with defines like `logError_CannotRemoveConnectorFromBusInTlmSystem(connector,bus)`?

**Comment by robbr48** [comment]
The error mentioned above is of course weird anyway, since TLM systems cannot have buses. It should probably say "TLM bus connector <bus> not found in system <system>".
