### ISSUE TITLE
Add Linux builds

### ISSUE THREAD

**Issue by meek1** [OpenModelica/OMSimulator#559]
Please add pre-compiled binaries for "generic Linux usage" on github (as already done for Windows). Should include both native FMI and TLM-functionality, and work for e.g. CentOS6 and 7. SysIdent may be omitted if problematic.

**Comment by meek1** [comment]
@sjoelund, @lochel Any progress on this one?

**Comment by sjoelund** [comment]
I have made some progress. Still trying to figure out how to not link some dynamic versions of system libraries in cmake. However, @lochel would need to remove the boost dependencies or add them to 3rdParty and compile static versions using -fPIC if we want to use the Python interface. It seems all Linux distributions compile their static Boost libraries without -fPIC, which only works on 32-bit OS.

**Comment by sjoelund** [comment]
#586 adds Linux builds to [our Jenkins](https://test.openmodelica.org/jenkins/job/OMSimulator/job/master/lastCompletedBuild/artifact/) (not last successful build because @lochel doesn't use our Jenkins, but our Hudson and as such the tests are usually slightly broken; it will take a while before this is updated, so I will attach a static build to this comment: [OMSimulator-linux-amd64-v2.1.0-dev-10-g5c19e85.tar.gz](https://github.com/OpenModelica/OMSimulator/files/2787090/OMSimulator-linux-amd64-v2.1.0-dev-10-g5c19e85.tar.gz))

Note that it is built using MUSL C and not GNU C since this is much easier with static linking. However, the TLM Simulator does not seem to support it. I did not try OMSysIdent. I tested the binary on CentOS6 (among others):
```bash
$ sudo docker run -it -w $HOME/Downloads -v $HOME/Downloads:$HOME/Downloads centos:6 ./bin/OMSimulator -v
OMSimulator v2.1.0-dev-10-g5c19e85-linux-notlm
```

The alpine:edge OS had boost with -fPIC so I could compile it with Boost and not rely on C++17 or rewriting existing code.

**Comment by lochel** [comment]
We are now using Jenkins and Windows, Linux, and Mac builds are available here: https://test.openmodelica.org/jenkins/job/OMSimulator/job/master/lastSuccessfulBuild/artifact/

This is now also linked from the README.

**Comment by lochel** [comment]
Can this be closed?

**Comment by sjoelund** [comment]
I think so. We now generate a dynamically linked version (so FMUs can be loaded), with static-libgcc and c++ that should work on any system with a GNU libc newer or same as the version shipped with CentOS6 (which is what we used to create the executable).
