### ISSUE TITLE
Unexpected initialization behavior

### ISSUE THREAD

**Issue by meek1** [OpenModelica/OMSimulator#667]
Now opening a separate issue with reference to #663: We noticed that different things happen depending on where you set initial values, i.e. prior to instantiate(), after instantiate() but prior to initialize(), or after initialize(). What is the general recommendation? Always set all start values prior to instantiate()?

See attached simple test model with two low-pass filters. One start value for each filter. Only start values set prior to instantiate() gives expected behavior. Setting both start values after instantiate() but prior to initialize() gives unexpected behavior for both filters. Then moving one start value down to after initialize() "heals" the behavior of the filter with start value set prior to initialize().

The example FMU is generated on Linux, let me know if you want to test also on Windows.

[filt.zip](https://github.com/OpenModelica/OMSimulator/files/3114088/filt.zip)

**Comment by lochel** [comment]
Can you please also share the Modelica model of the FMU?

**Comment by meek1** [comment]
Here it is!

[filt_FMU.zip](https://github.com/OpenModelica/OMSimulator/files/3119975/filt_FMU.zip)

**Comment by meek1** [comment]
@lochel, have you been able to reproduce the problem?

**Comment by lochel** [comment]
Yes, indeed! However, I have been investigating a different problem the last days related to event communication in the co-simulation master. I will come back with a detailed answer on this issue on Friday.

**Comment by lochel** [comment]
It seems everything makes sense and works as expected. `Modelica.Blocks.Continuous.FirstOrder` contains a state `y` which gets initialized using a parameter `y_start`.

**Before instantiation**
In this model state it is possible to set start values and initial unknowns (e.g. parameter `y_start`). They are not applied immediately, because the FMUs are not instantiated. Instead, they get stored and applied after instantiation.

**After instantiation, before initialization (initialization)**
In this model state it is possible to set start values and initial unknowns (e.g. parameter `y_start`) and the initial equations will be executed to calculate a valid initial model state.

**After initialization (simulation)**
The initial equations are no longer executed. Instead, the simulation equation will be executed. Changing parameter `y_start` has therefore no impact on the state `y` anymore. Instead, the state `y` can be changed directly, introducing a discrete change of a continuous variable which is not recommended.

**Comment by meek1** [comment]
OK, but what about the ”healing”?

**Comment by lochel** [comment]
Not sure. Which start value did you move after `oms_initialize`?

**Comment by meek1** [comment]
If I remenber it correctly, moving one (any one) of them heals the other one.

**Comment by lochel** [comment]
I think I tested that scenario and got expected (and correct) results. Can you send me a lua script with the respective calling sequence?
