### ISSUE TITLE
Install Python module OMSimulator with pip

### ISSUE THREAD

**Issue by AnHeuermann** [OpenModelica/OMSimulator#772]
For the OpenModelica Python interface it is possible to install it with
```bash
$ pip3 install OMPython
```
It would be great to have the same option for OMSimulator Python interface.

Currently I can only use OMSimulator from Python when I run `OMSimulatorPython`.
Is there currently a way to install the module?
My Linter is complaining all the time `Unable to import 'OMSimulator'pylint(import-error)`.

**Comment by superlou** [comment]
So, this is probably not the right way to do it, but to avoid needing to run `OMSimulatorPython .`, I set up my project like this by copying `libOMSimulator.so` and `OMSimulator.py` from the build of OMSimulator:

```
|-- oms/
|   |-- libOMSimulator.so   # I'm on Linux, would use the DLL on Windows
|   `--  OMSimulator.py
|-- main.py
```

With Python 3, I could then import OMS in `main.py` by:

```
from oms.OMSimulator import OMSimulator
```

I had to modify the line that loads the library in `OMSimulator.py` to match the new relative path: `self.obj=cdll.LoadLibrary("./oms/libOMSimulator.so")`. It would be better to use the `__file__` magic strings so that it isn't dependent on where you run the Python script from.

**Comment by AnHeuermann** [comment]
@superlou Thanks, I did a similar thing to your suggestion:
```python
import sys
sys.path.append("/opt/OMSimulator-dev-181/lib")
from OMSimulator import OMSimulator
```
That's enough for me, but not very user friendly.

I needed to change OMSimulator.py as well. Also it depends on the OMSimulator.so location. That changes depending how you build OMSimulator (standalone or with OpenModelica) or download the artifacts from Jenkins.

**Comment by arun3688** [comment]
@ setup file is available, package has to be uploaded to windows

**Comment by arun3688** [comment]
@ this is implemented now with https://github.com/OpenModelica/OMSimulator-pip/pull/7, now we can use` pip install OMSimulator`
