### ISSUE TITLE
Add __enter__ and __exit__ to Python class

### ISSUE THREAD

**Issue by AnHeuermann** [OpenModelica/OMSimulator#777]
## Problem
When using python module OMSimulator it would be nice to be able to exit a OMSimulator session.

It would be nice to use Pythons `with` statement:
```python
with OMSimulator() as oms:
  oms.getVersion()
```

**Priority**: Low (nice to have but not a real issue)

## Possible solution
Adding `__enter__` and `__exit__` to [OMSimulator.py.in](https://github.com/OpenModelica/OMSimulator/blob/master/src/OMSimulatorPython/OMSimulator.py.in) should do the trick.

**Comment by superlou** [comment]
I started looking at this, and it's not as straightforward as I thought. My assumption is that we want the `with` statement to clean-up the simulation when terminated. To me, that would be calling `terminate` and `delete`. However, since those two functions require a cref. In the documentation I've seen, the typical process is to have a single model named `model`, with various sub-models underneath that root. If that's the case, the following is sufficient:

```
  def __enter__(self):
    return self.newModel('model')

  def __exit__(self, type, value, traceback):
    self.terminate('model')
    self.delete('model')
```

Alternatively,  we could have `__enter__` do nothing, and keep track of successfully added models each time `newModel` is called. Then the `__exit__` method will clean up all models. Which of these approaches is preferred?

The other thing I noticed is that `setTempDirectory` needs to be called before adding models. Because of this, the most straightforward way is to add a parameter to the constructor:

```
class OMSimulator:
  def __init__(self, temp_directory=None):
    self.obj=cdll.LoadLibrary("@OMSIMULATORLIB_STRING@")
    ...
    if temp_directory is not None:
        self.setTempDirectory(temp_directory)
```

That should be backwards compatible with everyone's usage of `OMSimulator.py`, but it's technically an API change, so I wanted to mention it.

**Comment by superlou** [comment]
The model-tracking approach looks like this:

```python
class OMSimulator:
  def __init__(self, temp_directory=None):
    self.obj=cdll.LoadLibrary("@OMSIMULATORLIB_STRING@")

    ## oms_status_enu_t
    self.status_ok = 0
    self.status_warning = 1
    self.status_discard = 2
    self.status_error = 3
    self.status_fatal = 4
    self.status_pending = 5
    ...
    self.models = []

    if temp_directory is not None:
        self.setTempDirectory(temp_directory)

  def __enter__(self):
    return self

  def __exit__(self, type, value, traceback):
    for model in self.models:
      self.terminate(model)
      self.delete(model)

  def newModel(self, cref):
    status = self.obj.oms_newModel(self.checkstring(cref))
    if status == self.status_ok:
        self.models.append(cref)
    return status

  def delete(self, cref):
    status = self.obj.oms_delete(self.checkstring(cref))
    if status == self.status_ok:
        self.models = [model for model in self.models if model != cref]
    return status
```

If that methodology agrees with the intent of the API, I'll create a pull-request.

**Comment by AnHeuermann** [comment]
I think we should move `self.obj=cdll.LoadLibrary("@OMSIMULATORLIB_STRING@")` to `def __enter__(self):`:
Then the `__exit__` call could unload the dll:
```python
def __exit__(self, type, value, traceback):
  del self.obj
```

Feel free to start a pull request and we see if it's working as we want it to be.

But to be honest I'm not using Python much and don't know what a typical solution would look like for this.

**Comment by superlou** [comment]
My understanding, which seems to agree with https://stackoverflow.com/questions/359498/how-can-i-unload-a-dll-using-ctypes-in-python, is that calling `del` won't really unload anything. You're still at the whim of the garbage collector. The advantage of loading it prior to `__enter__` is that it continues to let you use the class without the `with` statement, which is pretty typical of APIs in my experience. I'll try to make a PR tonight.
